name: CI/CD MLflow

permissions:
  contents: write
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProjects/Predictive_Maintenance_Preproces.csv"
  TARGET_VAR: "Maintenance-Prediction"

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn numpy

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProjects/conda.yaml
          activate-environment: Maintenance-Prediction
          auto-activate-base: false

      - name: Clean old mlruns
        run: |
          rm -rf MLProjects/mlruns

      - name: Set MLflow tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=file://$GITHUB_WORKSPACE/MLProjects/mlruns" >> $GITHUB_ENV
          
      - name: Run MLflow Project
        run: |
          cd MLProjects
          mlflow run . -P data_path=Predictive_Maintenance_Preproces.csv --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td $GITHUB_WORKSPACE/MLProjects/mlruns/0/*/ 2>/dev/null | head -n 1 | awk -F/ '{print $(NF-1)}')
          if [ -z "$RUN_ID" ]; then
            echo "No MLflow run found! Exiting."
            exit 1
          fi
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: List MLruns folder (debug)
        run: |
          echo "Listing MLProjects/mlruns/0/$RUN_ID/artifacts/"
          ls -R MLProjects/mlruns/0/$RUN_ID/artifacts/
          
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com" 
          git add MLProjects/
          git commit -m "Save mlruns from CI run" || echo "No changes to commit" 
          git push

      - name: Build Docker Image from MLflow model
        run: |
            source ~/.bashrc
            conda activate Maintenance-Prediction
            mlflow models build-docker --model-uri "file://$GITHUB_WORKSPACE/MLProject/mlruns/0/$RUN_ID/artifacts/model" --name cc

          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
